export const SET_DIVISIONS_LIST = "SET_DIVISIONS_LIST";
export const ADD_DIVSION_POINTS = "ADD_DIVSION_POINTS";
export const UPDATE_TABLE_LEADER = "UPDATE_TABLE_LEADER";

export const SET_FIGHTERS_LIST = "SET_FIGHTERS_LIST";
export const UPDATE_FIGHTER_ROUND_RESULT = "UPDATE_FIGHTER_ROUND_RESULT";

export const SET_DIVISION_TABLE = "SET_DIVISION_TABLE";
export const ADD_DIVISION_ROUND_POINTS = "ADD_DIVISION_ROUND_POINTS";

export const SET_ROUNDS_LIST = "SET_ROUNDS_LIST";
export const SET_ROUND_RESULT = "SET_ROUND_RESULT";

export const UPDATE_FIGHTER_IMGS = "UPDATE_FIGHTER_IMGS";

export const SET_NEWS = "SET_NEWS";

export const SET_FINAL_RANKINGS = "SET_FINAL_RANKINGS";
export const ADD_FINAL_RANKINGS = "ADD_FINAL_RANKINGS";
export const FETCH_FINAL_RANKINGS = "FETCH_FINAL_RANKINGS";
